### ISSUE TITLE
Bug? Empty MQTT QoS 1 messages

### ISSUE THREAD

**Issue by StenGruener** [iitsoftware/swiftmq-ce#77]
Dear team,

I test swiftmq-ce (from docker hub) with publishers and subscribers based on pyhton eclipse paho. I observe that some of the messages received by subscribers are arriving empty (\x00 bytes). For me it looks randomly, happens probably every 500th message, depending on rate/load.

Any idea?

**Comment by iitsoftware** [comment]
If you replace this config in the `sys$trace` section of your `data/config/routerconfig.xml` and re-run your test, you'll find all traces under `data/trace/mqtt.trace`:

```
      <space name="kernel" enabled="true">
        <predicates>
          <predicate name="22" filename="../data/trace/mqtt.trace" value="sys$mqtt"/>
        </predicates>
      </space>

```

Please have a look and let me know if you find something.
